language: java
jdk: oraclejdk8
install: true
script:
- 'gradle clean check jacocoTestReport'
after_success:
- 'bash <(curl -s https://codecov.io/bash)'
- 'if [ "${TRAVIS_BRANCH}" = "staging" ]; then
     OSSRH_URL="${OSSRH_URL_STAGING}";
   fi'
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
     openssl aes-256-cbc
       -K "${encrypted_c895e68ef476_key}"
       -iv "${encrypted_c895e68ef476_iv}"
       -in secring.gpg.enc -out secring.gpg -d;
     gradle clean build publish
       -Psigning.keyId="${SIGNING_KEY_ID}"
       -Psigning.password="${SIGNING_PASSWORD}"
       -Psigning.secretKeyRingFile="${SIGNING_SECRET_KEY_RING_FILE}";
   fi'
