language: java
jdk: oraclejdk8
install: true
before_install:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
     openssl aes-256-cbc
       -K "${encrypted_c895e68ef476_key}"
       -iv "${encrypted_c895e68ef476_iv}"
       -in secring.gpg.enc -out secring.gpg -d;
   fi'
script:
- 'if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
     gradle clean check jacocoTestReport;
   fi'
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
     gradle clean build jacocoTestReport
       -Psigning.keyId=${SIGNING_KEY_ID}
       -Psigning.password=${SIGNING_PASSWORD}
       -Psigning.secretKeyRingFile=${SIGNING_SECRET_KEY_RING_FILE};
   fi'
after_success:
- 'bash <(curl -s https://codecov.io/bash)'
