language: java
jdk:
- oraclejdk8
script:
- gradle clean check jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
dd:
- openssl aes-256-cbc -K $encrypted_c895e68ef476_key -iv $encrypted_c895e68ef476_iv
  -in secring.gpg.enc -out secring.gpg -d
